baseURL = "https://example.com/"
languageCode = "en-us"
title = "Hugo-HT"
theme = "hugo-ht"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"

[[menu.en]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.en]]
    name = "教程"
    url = "/tutorials/"
    weight = 2

[params]
    description = "Peronal website of Your Name"
    homeText = "You just need a Hugo blog from scratch"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs" 
    MathJaxVersion = "2.7.5"
    favicon = "/ht10.ico"
    footer = "&copy; Your Name 2021"

[params.logo]
  url = "hugo-logo.png"
  width = 50.0
  height = 50.0
  alt = "Hugo-ht"

  [params.author]
  en = "Your Name"
  cn = "你的名字"

  [params.lang]

    [params.lang.edit]
    en = "Suggest an edit of this page"
    cn = "编辑本页"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100
      
